### ISSUE TITLE
Brackets inside codeblocks recognised as links

### ISSUE THREAD

**Issue by ekamil** [ulisesantana/obsidian-pending-notes#1]
Hi,
Seems that code blocks aren't excluded from pending notes which results in spurious entries in the "pending notes list". 
Example:
```zsh
# ${ZSH_CUSTOM}/volta.zsh
VOLTA_HOME="$HOME/.volta"
if [[ -d $VOLTA_HOME ]]; then
    path=("$VOLTA_HOME/bin" $path)
    export PATH
    export VOLTA_HOME
fi
```
<img width="944" alt="Screenshot 2023-01-23 at 00 13 26" src="https://user-images.githubusercontent.com/1164694/213945525-08fcb086-7e42-4a2d-924b-2d4bd23a4b02.png">

**Comment by ulisesantana** [comment]
Thanks for your time writing the issue! 

This is fixed on [version 0.5.1](https://github.com/ulisesantana/obsidian-pending-notes/releases/tag/0.5.1)
