### ISSUE TITLE
Feature request: Show count (and sort by count option)

### ISSUE THREAD

**Issue by freshgruts** [ulisesantana/obsidian-pending-notes#6]
It would be really useful if we could see *how many* existing notes link to the pending note (especially if we could also sort by count). A pending note with 10 other notes linking to it is of greater priority for me than a pending note with only one other note linking to it.

**Comment by ulisesantana** [comment]
That makes a lot of sense. I really love the idea, thanks. I mean it. As soon as I have no pending bugs to fix I will start with this.

I'm wondering if this feature should be by default or even the only way to show pending notes. What do you think?

Again, thank you for writing the issue and suggesting the feature.

**Comment by ulisesantana** [comment]
At the end let this behaviour as the only one. You can start using it on [version 0.6.0](https://github.com/ulisesantana/obsidian-pending-notes/releases/tag/0.6.0).

If you have any idea or suggestion, please feel free to write a comment.
