### ISSUE TITLE
Stale data

### ISSUE THREAD

**Issue by mariomui** [ulisesantana/obsidian-pending-notes#9]
As a note taker, i sometimes leave the plugin's leafview open after creating a pending-note. The pending note's information does not have the up to date information from the newly created note.  

* Not having a refresh button on the pending notes view can cause the plugin to show stale data when there has been more pending-notes added after ui has been rendered on the side leaf.

**Comment by ulisesantana** [comment]
Done! Thanks for raising the issue and suggesting the solution.
